name: qnst
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - numpy>=1.21.0
  - pytorch>=2.0.0
  - cudatoolkit>=11.8
  - mne>=1.4.0
  - scipy>=1.7.0
  - pandas>=1.3.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - scikit-learn>=0.24.0
  - pytest>=6.2.5
  - black>=21.7b0
  - isort>=5.9.3
  - flake8>=3.9.0
  - mypy>=0.910
  - pip
  - pip:
    - qiskit>=0.33.0
    - pennylane>=0.20.0
    - tensorflow>=2.6.0
    - asyncio>=3.4.3
    - aiohttp>=3.8.0
    - pyyaml>=5.4.1
    - tqdm>=4.62.0
    - pyserial>=3.5
