from setuptools import setup, find_packages

setup(
    name="qnst",
    version="0.1.0",
    description="Quantum Neural Substrate Transfer Project",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    author="QNST Research Team",
    author_email="qnst@research.org",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    install_requires=[
        "numpy>=1.21.0",
        "qiskit>=0.33.0",
        "pennylane>=0.20.0",
        "torch>=1.9.0",
        "tensorflow>=2.6.0",
        "scipy>=1.7.0",
        "pandas>=1.3.0",
        "matplotlib>=3.4.0",
        "seaborn>=0.11.0",
        "asyncio>=3.4.3",
        "aiohttp>=3.8.0",
        "pyyaml>=5.4.1",
        "tqdm>=4.62.0",
        "scikit-learn>=0.24.0",
        "pyserial>=3.5",
    ],
    extras_require={
        "dev": [
            "pytest>=6.2.5",
            "black>=21.7b0",
            "isort>=5.9.3",
            "flake8>=3.9.0",
            "mypy>=0.910",
        ]
    },
    python_requires=">=3.8",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "Topic :: Scientific/Engineering :: Physics",
        "Topic :: Scientific/Engineering :: Neuroscience",
    ],
)
