name: "Bug Report"
description: "File a bug report"
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      placeholder: ex. v0.1.0
    validations:
      required: true

  - type: dropdown
    id: components
    attributes:
      label: Which component is affected?
      multiple: true
      options:
        - Neural Mapping
        - Quantum Substrate
        - Robotic Interface
        - Consciousness Transfer
        - Safety Systems
        - Other
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code.
      render: shell
