name: "Feature Request"
description: "Suggest an idea for this project"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: Please describe what problem you're trying to solve.
      placeholder: A clear and concise description of what the problem is.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: What would you like to see implemented?
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: dropdown
    id: components
    attributes:
      label: Which component would this affect?
      multiple: true
      options:
        - Neural Mapping
        - Quantum Substrate
        - Robotic Interface
        - Consciousness Transfer
        - Safety Systems
        - Other
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: What other solutions have you thought about?

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the feature request here.
